services:
  - type: worker
    name: wsi-20-userbots
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOTS_CONFIG
        sync: false
